spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc-url: ${DB_URL}/business
    url: ${DB_URL}/business
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  redis:
    notice:
      host: 127.0.0.1
      port: 6379  # live: 6379
      sentinel:
        master: noticemaster
        nodes: 127.0.0.1:26379,127.0.0.1:26380    # live : 26379-26381
      lettuce:
        shutdown-timeout: 200ms

#다중 DB 연결 예정
#  second-datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: ${DB_URL}/log
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: watson-house
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com.watson.business: debug
    org.hibernate.SQL: debug