spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # "create"을 사용하면 애플리케이션 시작 시에 테이블을 새로 생성합니다. 주의해서 사용해야 합니다.
    show-sql: true # Hibernate가 생성하는 SQL을 콘솔에 출력합니다. 개발 환경에서 유용합니다.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect