spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/business
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    notice:
      host: 127.0.0.1
      port: 6379  # live: 6379
      sentinel:
        master: noticemaster
        nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381    # live : 26379-26381
      lettuce:
        shutdown-timeout: 200ms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb

server:
  port: 8082