# server setting
server:
  port: 8080

# spring setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/auth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # spring security
  security:
    code: ${SECURITY_CODE}
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KCLIENT-ID}
            client-secret: ${KCLIENT-SECRET}
            client-authentication-method: POST
            redirect-uri: ${K-REDIRECT}
            client-name: Kakao
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update # create

  redis:
    auth:
      host: I9A803.p.ssafy.io # 127.0.0.1
      port: 6379  # live: 6379
      sentinel:
        master: authmaster
        nodes: I9A803.p.ssafy.io:26379,I9A803.p.ssafy.io:26380,I9A803.p.ssafy.io:26381    # live : 26379-26381 // 사용하는 포트번호
      lettuce:
        shutdown-timeout: 200ms

# jwt
jwt:
  secret: ${JWT-SECRET}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: watson-house # S3에 버킷은 하나
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false